name: inGitDB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ingitdb:
    name: Validate & Materialize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate schema & data
        uses: ingitdb/ingitdb-action@main
        with:
          args: validate

      - name: Materialize views
        uses: ingitdb/ingitdb-action@main
        with:
          args: materialize
